### ISSUE TITLE
Some questions about experiment

### ISSUE THREAD

**Issue by ChenSiyi1** [wangchi95/CF-Font#10]
对您的工作很感兴趣，但在实验中遇到一些问题：
1. 在自己的数据集上（240 fonts，800 characters）训练，batchsize从16调到32，其他设置不变，训练时间变长（近乎翻倍），评价指标fid变得更差了，其他指标多少都有提升，不是很理解什么原因导致fid结果更差了？
2. 训练base network的时候，如何设定source font? 把宋体或楷体放在id_0？
3. 在option_run_inf_dgfont.sh 中，
`# > cp -rf Seen240_S80F50_FS16 Seen240_S80F50_FS16_DGFONT`
`# > cp -rf Seen240_S80F50_TEST5646/id_0 Seen240_S80F50_FS16_DGFONT/id_240`
我理解为在数据集Seen240_S80F50_FS16_DGFONT中，设置id_0到id_239为style images，id_240为source images，不知道是不是这个意思。
希望能得到您的回复，非常感谢！

**Comment by wangchi95** [comment]
1. 可以看一下batch16的生成结果是不是更清晰一些。FID指标表现确实有点奇怪，我们现在也不确定FID针对字体生成任务（灰度，边界较为明显的图片）进行评估是否合适，我们以及前人论文或多或少也都提及这一点，FID似乎更关注于图片请不清晰。你可以看字体生成的一系列论文，FID有时和其他指标有歧义，会出现一些方法各指标都差但是FID很高的情况。甚至在rebuttal期间，我们和审稿人也对此问题做了探讨，能不能有更符合人类直觉的指标。
2. 训练basefont应该不是固定source font的，id_0随意放就行。（任何字体都可以作为source）
3. 你的理解是正确的。
