### ISSUE TITLE
請問 Unseen60_S80F50 的資料夾裡也是要放字體的嗎？

### ISSUE THREAD

**Issue by bhhsieh** [wangchi95/CF-Font#11]
在執行 
`sh scripts/03d_cal_cf_weights.sh`
時，出現錯誤訊息
`RuntimeError: Found 0 files in subfolders of: data/imgs/Unseen60_S80F50_FS16
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,webp`

想請問一開始也需要在 Unseen60_S80F50 裡面放字體嗎？
看你的 How to run 教學裡面第一步 prepare dataset 中，Unseen60_S80F50 資料夾裡似乎也是空的？

**Comment by wangchi95** [comment]
@bhhsieh Unseen60_S80F50文件夹需要放字体的，不过这和训练过程完全无关，主要是验证算法在unseen字体上的能力，如果你没有类似的需求（生成训练过程没见过的字体）也可以把unseen相关部分注释掉。

Unseen60_S80F50里面的图片不一定需要通过第一步生成，如果是设计师使用的话，只需要提供fewshot对应的字符图片，手动按顺序放进去即可。

**Comment by bhhsieh-icrr** [comment]
@wangchi95 感謝回答！
想再請教一下關於 style interpolation 的部分。
在做 `04a_run_inf_cf.sh` 的時候，需要給 target_style 和對應的權重 basis_ws，這兩者是一一對應的。
我能將 basis_ws 做 interpolation，但 target_style 要如何做 interpolation 呢？

**Comment by wangchi95** [comment]
@bhhsieh 我们按照常规styleGAN风格插值的方式进行target_style的插值。具体来说，针对两个字体A和B，我们能得到对应的basis_ws pair和style vector pair，然后分别进行线性插值。

**Comment by bhhsieh-icrr** [comment]
@wangchi95 了解！非常感謝您的回覆！
