### ISSUE TITLE
关于编译DCN的问题

### ISSUE THREAD

**Issue by sirius1114** [wangchi95/CF-Font#15]
你好，在编译DCN中，老是报错，现在卡在这个错误：RuntimeError: Error compiling objects for extension。 我的torch版本是2.0.1+cu118；cuda是11.8；cudnn是8700。（我感觉可以排除torch与cuda版本不匹配的可能性）

**Comment by sirius1114** [comment]
<img width="887" alt="微信截图_20230714180257" src="https://github.com/wangchi95/CF-Font/assets/130277767/56fb7603-81b1-42bb-ae12-b6d965fca0f3">
<img width="710" alt="微信截图_20230714180322" src="https://github.com/wangchi95/CF-Font/assets/130277767/d03161d1-0bee-4160-a0cc-aac51ae37fc7">
错误挺长的 截取了开头和结尾

**Comment by wangchi95** [comment]
@sirius1114 可能是torch版本太新了（那个branch是针对pytorch1.x.x的），可以去DCN的官方repo问一下。

**Comment by wangchi95** [comment]
这个issue先关闭了，如果有进一步问题，可以继续问我:)
