### ISSUE TITLE
请问训练的时候Gloss为NaN是什么原因呢？

### ISSUE THREAD

**Issue by sunyuanrui** [wangchi95/CF-Font#16]
![深度截图_选择区域_20230718191410](https://github.com/wangchi95/CF-Font/assets/12118982/9d5fe64a-0622-42bf-983c-6223d64103c5)

**Comment by yishuaidu** [comment]
我怀疑 应该是ttf文件文字不全，gen的时候生成了白色图，我也出现了

**Comment by sunyuanrui** [comment]
> 我怀疑 应该是ttf文件文字不全，gen的时候生成了白色图，我也出现了

是的，把这个ttf删除就好了

**Comment by yishuaidu** [comment]
> 

能看下你的训练曲线吗？你收敛的快不？

**Comment by sunyuanrui** [comment]
挺快的，我只用了60种字体，30 epoch之后就开始振荡了
![深度截图_选择区域_20230728153656](https://github.com/wangchi95/CF-Font/assets/12118982/df092688-8d5a-4a38-a6bb-1852087627bb)

**Comment by yishuaidu** [comment]
> 挺快的，我只用了60种字体，30 epoch之后就开始振荡了 ![深度截图_选择区域_20230728153656](https://user-images.githubusercontent.com/12118982/256756271-df092688-8d5a-4a38-a6bb-1852087627bb.png)

我好奇怪， 我一共300个字体， 240 see， 60 unsee ， 收敛太快了， 有点不正常， 你设置都是和他一样默认的嘛？

能问下你的联系方式么？ 请教下您

**Comment by sunyuanrui** [comment]
你用scripts/option_run_inf_dgfont.sh推理看看效果如何，你loss曲线是啥样的？

**Comment by sunyuanrui** [comment]
> > 挺快的，我只用了60种字体，30 epoch之后就开始振荡了 ![深度截图_选择区域_20230728153656](https://user-images.githubusercontent.com/12118982/256756271-df092688-8d5a-4a38-a6bb-1852087627bb.png)
> 
> 我好奇怪， 我一共300个字体， 240 see， 60 unsee ， 收敛太快了， 有点不正常， 你设置都是和他一样默认的嘛？
> 
> 能问下你的联系方式么？ 请教下您


你用scripts/option_run_inf_dgfont.sh推理看看效果如何，你loss曲线是啥样的？

**Comment by yishuaidu** [comment]
> > > 挺快的，我只用了60种字体，30 epoch之后就开始振荡了 ![深度截图_选择区域_20230728153656](https://user-images.githubusercontent.com/12118982/256756271-df092688-8d5a-4a38-a6bb-1852087627bb.png)
> > 
> > 
> > 我好奇怪， 我一共300个字体， 240 see， 60 unsee ， 收敛太快了， 有点不正常， 你设置都是和他一样默认的嘛？
> > 能问下你的联系方式么？ 请教下您
> 
> 你用scripts/option_run_inf_dgfont.sh推理看看效果如何，你loss曲线是啥样的？

貌似正常了 。。。 着急了 感谢

**Comment by yishuaidu** [comment]
> > > 挺快的，我只用了60种字体，30 epoch之后就开始振荡了 ![深度截图_选择区域_20230728153656](https://user-images.githubusercontent.com/12118982/256756271-df092688-8d5a-4a38-a6bb-1852087627bb.png)
> > 
> > 
> > 我好奇怪， 我一共300个字体， 240 see， 60 unsee ， 收敛太快了， 有点不正常， 你设置都是和他一样默认的嘛？
> > 能问下你的联系方式么？ 请教下您
> 
> 你用scripts/option_run_inf_dgfont.sh推理看看效果如何，你loss曲线是啥样的？

你有试过 img_size=128  chara_size=80  嘛？ 效果如何？ 我推理出来变成花色了。 不知道咋回事.

**Comment by sunyuanrui** [comment]
> > > > 挺快的，我只用了60种字体，30 epoch之后就开始振荡了 ![深度截图_选择区域_20230728153656](https://user-images.githubusercontent.com/12118982/256756271-df092688-8d5a-4a38-a6bb-1852087627bb.png)
> > > 
> > > 
> > > 我好奇怪， 我一共300个字体， 240 see， 60 unsee ， 收敛太快了， 有点不正常， 你设置都是和他一样默认的嘛？
> > > 能问下你的联系方式么？ 请教下您
> > 
> > 
> > 你用scripts/option_run_inf_dgfont.sh推理看看效果如何，你loss曲线是啥样的？
> 
> 你有试过 img_size=128 chara_size=80 嘛？ 效果如何？ 我推理出来变成花色了。 不知道咋回事.

估计是没加载权重吧，作者自己说128效果也不错
