### ISSUE TITLE
由于ttf的原因，有些字体缺失导致处理的时候有白图，这种要删掉嘛？谢谢

### ISSUE THREAD

**Issue by yishuaidu** [wangchi95/CF-Font#17]
1. 由于ttf的原因，有些字体缺失导致处理的时候白图，这种要删掉嘛？
2. 删掉后 id_x 后面的文件之前是排序的，say 0-6762，  举个例子 我在Seen240_S80F50_FULL文件夹下的某个id文件下删掉了白图，然后0-6762不是连续了，会丢几张，会不会影响我后面  sh scripts/01b_copy_subset.sh  这一步呢？ 

谢谢

**Comment by sunyuanrui** [comment]
我是直接删除ttf了，如果这个ttf不是特别重要的话建议删除，如果比较重要的话，可以考虑手动生成16个字符后放到Unseen60_S80F50_FS16，推理的时候使用验证一下效果

**Comment by sunyuanrui** [comment]
可能会影响 sh scripts/01b_copy_subset.sh ，如果charset/TRAIN800.txt里面的字符都有就不受影响，训练的时候只用这800个字符，剩下的都作为测试使用了

**Comment by yishuaidu** [comment]
> 可能会影响 sh scripts/01b_copy_subset.sh ，如果charset/TRAIN800.txt里面的字符都有就不受影响，训练的时候只用这800个字符，剩下的都作为测试使用了

ok 谢了
