### ISSUE TITLE
typo in 03d_cal_cf_weights.sh

### ISSUE THREAD

**Issue by yishuaidu** [wangchi95/CF-Font#18]
if [ $option == 'seen' ];then
....
elif [ $option == 'unseen' ]; then
....

I got something wrong with 

scripts/03d_cal_cf_weights.sh: 19: [: seen: unexpected operator
scripts/03d_cal_cf_weights.sh: 25: [: seen: unexpected operator

It should be:

if [ $option = 'seen' ];then
....
elif [ $option = 'unseen' ]; then
....

**Comment by wangchi95** [comment]
https://stackoverflow.com/questions/20449543/shell-equality-operators-eq

Thanks for pointing out, according to the above link: 
> `==` is specific to bash (not present in sh (Bourne shell), ...). Using POSIX `=` is preferred for compatibility. In bash the two are equivalent, and in sh = is the only one that will work.

And I have tested in bash and zsh, both are available.

**Comment by yishuaidu** [comment]
tyty
