### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SidraHanif180** [wangchi95/CF-Font#2]
Hi,

Thanks for the great work. 
When are you planning to release the code?

**Comment by wangchi95** [comment]
> Hi,
> 
> Thanks for the great work. When are you planning to release the code?

Thanks for your interest in our work. It might take around 10 days to finish organizing the code and obtain the open-source code approval from Alibaba Group.

I will update the repository as soon as possible.

**Comment by wangchi95** [comment]
The code has been released~
