### ISSUE TITLE
关于字库补全的问题

### ISSUE THREAD

**Issue by xiao-wj** [wangchi95/CF-Font#20]
您好，想问下这里用到了常用的中文字符6000多，实际用到800多来训练，但推理的时候我希望把某个字体所支持的全部字符（可能包含两三万个字符）都推理出来，但其实不是所有的seen字体都支持这2w多字符，可能支持的字符在8k-3w不等，这时候我需要修改训练的细节吗，以及这个方法的效果如何呢（ps：之前有尝试zi2zi的模型，其实在不同字体直接的差异还是有的，可能是没有很好的学习到字符样式的局部特征。）

**Comment by wangchi95** [comment]
不需要修改训练细节，唯一需要完整2w+字的就是几款基字体们。实验上800个字符进行训练基本就够了（已经能出一个比较好的结果了），如果计划工业上应用可以考虑加入更多字符训练。

听起来inference似乎会包含大量笔画较多的字符，推荐用更高分辨率（128x128）训练和推理，局部细节（骨架练笔和笔触）会好很多。由于我们不是通过单一字体进行迁移，而是参考多个基字体对内容特征进行估计，因此迁移相对容易一些，泛化能力会更好一些。

另：如果计划提升分辨率的话，推荐采用DG-Font++的网络作为backbone，参考其他issue。

**Comment by xiao-wj** [comment]
谢谢，我这里还有几个问题希望解答一下~
1. 我理解的是，TEST5646这个文件下的图片，只对基础字体管用（其他的训练字体只用到了TRAIN800），也就是用于模型的推理阶段？ 
2. 我还是没太明白这里Basis字体的设定，基础字体起到了什么关键性的作用呢（我看开始第二部训练前就需要选定好这个，说明也参与到第二步训练的过程），数量有要求吗，如果我只设置一款字体为基础字体会怎么样呢？
3. 我用的128*128的图片，换了一种方式来生成，使得字符尽可能居中，训练过程中发现dloss一直在下降，gloss一直在上升，感觉有点奇怪（虽然也算是一定程度的平衡了）

**Comment by wangchi95** [comment]
1. 训练只需要训练集的800个字符就行，inference的时候只有基字体需要有完整的字库用于提供content信息。
2. 基字体是本文的核心模块，基本思想基于Content 和 style 信息很难彻底分离，只用一个字体提取出的content信息带有一定噪声，我们用CFM通过多个字体来进一步探索content和style的同步。数量没有要求，我们试过5，10，20，效果都挺好的，如果目标字较为标准，推荐人工加入宋体。如果你只设置一款字体为基础字体，那其实就是我们用的基础网络DG-Font。
3. 训练过程相对平衡就行，gloss本来就会慢慢上涨的。（生成方式影响一般不会很大，我用的生成代码和DGFont也不一样，也稍微加了点自动居中。不过推荐加字体级别的居中而非字符级别的，不然对有些本来就不需要居中的字符可能会有影响。

**Comment by xiao-wj** [comment]
我在想几种基础字体的全部字符是有相同也有不同的，如果各自用自身支持的全部字符，（因为我最终目的可能是要还原某字体全部字符，如苹方3w5个），会有什么别的影响吗，这时候会不会出现idx映射不到的情况呢？

**Comment by wangchi95** [comment]
可以试试，如果基字体部分字符缺失的话确实可以通过直接置0（归一化前）取消某个基字体content的影响，但对结果应该会有一定影响，尤其是确实content weight大的几个基字体。

此外对骨骼形变的能力的会有影响。当然由于DGFont中FDSC的存在，本身基础网络就具有一定的局部骨骼形变能力，可能这种程度的形变对你的任务就足够了。（可以先拿DGFont试试效果

**Comment by xiao-wj** [comment]
您好，我这几天训练了个mini版本，128*128的图片，拿30个字体训练，第一论训练了60个epoch，第二轮40个，只用了一个作为basis字体，但不少笔画其实不太清晰，想问下这种有什么建议呢。（看起来是字符内容上的丢失，像是第一步训练不够或者基础字体太少了的原因）
<img width="809" alt="image" src="https://github.com/wangchi95/CF-Font/assets/31876626/c7032272-b109-47b6-8927-5d106eda5d08">
<img width="430" alt="image" src="https://github.com/wangchi95/CF-Font/assets/31876626/7ac6627a-0abe-41df-81ca-54004a915f3a">

**Comment by wangchi95** [comment]
@xiao-wj 首先是训练字体数目和迭代次数确实不大够，同时对于128分辨率的图像，推荐使用DGFont++作为backbone，清晰度和局部细节会有大幅提升<https://[arxiv.org/pdf/2212.14742.pdf](https://arxiv.org/pdf/2212.14742.pdf)>
DGFont因为跳连接设置的不合理在高分辨率上表现一般。

（另外，如果只用一个字体作为基字体的话，没必要加第二阶段

**Comment by xiao-wj** [comment]
好的，感谢你的回复，我看下怎么用DGFont++（最终可能还是得用256分辨率的图片），另外我打算用zi2zi还原几套字体，凑个十个基准字体看看效果。

**Comment by gagahamburger** [comment]
你好，我想请问一下，这个代码是否可以生成句子式的文字，而不是单个文字？

**Comment by zhenzi0322** [comment]
> @xiao-wj 首先是训练字体数目和迭代次数确实不大够，同时对于128分辨率的图像，推荐使用DGFont++作为backbone，清晰度和局部细节会有大幅提升[https://[arxiv.org/pdf/2212.14742.pdf](https://arxiv.org/pdf/2212.14742.pdf)](https://%5Barxiv.org/pdf/2212.14742.pdf%5D(https://arxiv.org/pdf/2212.14742.pdf)) DGFont因为跳连接设置的不合理在高分辨率上表现一般。
> 
> （另外，如果只用一个字体作为基字体的话，没必要加第二阶段

DGFont++的开源代码在哪里可以下载？

**Comment by wangchi95** [comment]
> 你好，我想请问一下，这个代码是否可以生成句子式的文字，而不是单个文字？

我们任务的着眼点不在这儿，字符之间是相对独立的。我记得去年CVPR有这方面的相关工作，可以了解一下。

**Comment by wangchi95** [comment]
> > @xiao-wj 首先是训练字体数目和迭代次数确实不大够，同时对于128分辨率的图像，推荐使用DGFont++作为backbone，清晰度和局部细节会有大幅提升[https://[arxiv.org/pdf/2212.14742.pdf](https://arxiv.org/pdf/2212.14742.pdf)](https://%5Barxiv.org/pdf/2212.14742.pdf%5D(https://arxiv.org/pdf/2212.14742.pdf)) DGFont因为跳连接设置的不合理在高分辨率上表现一般。
> > （另外，如果只用一个字体作为基字体的话，没必要加第二阶段
> 
> DGFont++的开源代码在哪里可以下载？

应该还没开源 可以自己实现一下

**Comment by zhenzi0322** [comment]
> > > @xiao-wj 首先是训练字体数目和迭代次数确实不大够，同时对于128分辨率的图像，推荐使用DGFont++作为backbone，清晰度和局部细节会有大幅提升[https://[arxiv.org/pdf/2212.14742.pdf](https://arxiv.org/pdf/2212.14742.pdf)](https://%5Barxiv.org/pdf/2212.14742.pdf%5D(https://arxiv.org/pdf/2212.14742.pdf)) DGFont因为跳连接设置的不合理在高分辨率上表现一般。
> > > （另外，如果只用一个字体作为基字体的话，没必要加第二阶段
> > 
> > 
> > DGFont++的开源代码在哪里可以下载？
> 
> 应该还没开源 可以自己实现一下

自己不会实现呢。
