### ISSUE TITLE
关于 sh scripts/02a_run_ddp.sh运行时的问题

### ISSUE THREAD

**Issue by gagahamburger** [wangchi95/CF-Font#22]
老师，您好。我在运行代码时遇到了一些问题：如图所示。在网上查到的意思是多线程出现了问题。然后我看代码有个todo：要删除那行代码。我删除之后还是会报错。请问一下该如何解决呢。 谢谢老师了
![Selection_002](https://github.com/wangchi95/CF-Font/assets/122259974/50c82d0a-e830-47b1-96a1-09fad2ca84d7)

**Comment by wangchi95** [comment]
@gagahamburger 那行没问题的，注释是本来想整体重写成更优雅的方式做的记号。

这看起来好像是DDP的问题，你是用单卡跑的么？（如果是的话需要把--nproc_per_node设成1，CUDA_VISIBLE_DEVICES设0即可）

如果本身就是用多卡的，可以考虑按提示传入CUDA_LAUNCH_BLOCKING=1看看有没有近一步提升

**Comment by MEIZU16** [comment]
@wangchi95 我使用多卡时感觉有点奇怪，相同batch size一张卡和两张卡一轮时间一样，而且两张卡显存占用和一张是一样的（比如一张卡跑是占19g，两张就是各占19g，时间还一样）

**Comment by wangchi95** [comment]
@MEIZU16 DDP的batch size是每张卡的（总BS是卡数*每张卡分配多少

**Comment by wangchi95** [comment]
这个issue先关闭了，如果有进一步问题，可以继续问我:)

**Comment by chiaoooo** [comment]
您好，由於我使用單卡，所以把 dist.init_process_group(init_method='env://', backend="nccl") 改成 gloo，但出現下面的錯誤，想請問有任何解法嗎？
![image](https://github.com/wangchi95/CF-Font/assets/62134746/69d21985-a56c-4002-8f05-84970436c59d)
