### ISSUE TITLE
如何执行推理生成一批新样式的字符图像？

### ISSUE THREAD

**Issue by zhenzi0322** [wangchi95/CF-Font#23]

**Comment by wangchi95** [comment]
不是很理解这个问题，能详细描述一下么？
理论上准备好数据，按READEME的流程就可实现此功能

**Comment by zhenzi0322** [comment]
好的，我在训练`cf-font`时最终预测出的目标字体不是很友好，如下

![image](https://github.com/wangchi95/CF-Font/assets/34839719/a6c98212-02f4-485f-9dd5-b6da62484624)

![image](https://github.com/wangchi95/CF-Font/assets/34839719/3e729d10-e1fb-47ca-8d8b-4d406ff985b4)

训练命令：

```
python main.py --data_path data/imgs/Seen240_S80F50_TRAIN800 --lr 1e-4 --output_k 240 --batch_size 16 --iters 1000 --epoch 6000 --val_num 10 --baseline_idx 0 --save_path output/models --model_name B0_K240BS32I1000E200_LR1e-4-wdl0.01 --wdl --w_wdl 0.01 --no_val
```

**Comment by zhenzi0322** [comment]
预测出来的目标字体，有的字好，有的字又不好，总体来看的话，是不太友好的效果。

**Comment by zhenzi0322** [comment]
我想请问一下，是不是训练参数我设置不对，导致最终预测的效果不友好？

**Comment by wangchi95** [comment]
不好意思，在赶DDL，不是很有时间看repo，如果你赶CVPR很着急的话可以加我微信(by-Angus

结果很不正常呀，按道理出来结果还是挺干净的
训练参数看起来也没有问题，这个是只训练了DGFont涉及的步骤么？如果是的话基字体用的是常规字体么（宋、楷）
如果训练了CF-Font模块的话，后面训练参数也给我看一下吧

还有，训练过程的中间结果看着正常么？

**Comment by zhenzi0322** [comment]
训练过程中的结果看着还正常，我采用模型预测非训练以外的字体的话结果就很不正常了。

**Comment by zhenzi0322** [comment]
训练的字体我采用各式各样类型的字体，可能其中有宋，楷，还会有毛笔等。准备的字体数量是240个字体

**Comment by zhenzi0322** [comment]
训练命令：
```
python main.py --data_path data/imgs/Seen240_S80F50_TRAIN800 --lr 1e-4 --output_k 240 --batch_size 16 --iters 1000 --epoch 6000 --val_num 10 --baseline_idx 0 --save_path output/models --model_name B0_K240BS32I1000E200_LR1e-4-wdl0.01 --wdl --w_wdl 0.01 --no_val
```

**Comment by wangchi95** [comment]
> 训练过程中的结果看着还正常，我采用模型预测非训练以外的字体的话结果就很不正常了。

我们结构的外插能力确实有限，但看起来你图中的数据没有突破特征空间呀，这很不正常

顺便问一下训练集unseen字符的效果呢？

**Comment by wangchi95** [comment]
> 训练的字体我采用各式各样类型的字体，可能其中有宋，楷，还会有毛笔等。准备的字体数量是240个字体

基本有较为标准的楷、宋、黑体之类的，再有一些手写或者毛笔行书和少量草书（不要缩笔过多的），覆盖范围就够了

**Comment by wangchi95** [comment]
> 训练命令：
> 
> ```
> python main.py --data_path data/imgs/Seen240_S80F50_TRAIN800 --lr 1e-4 --output_k 240 --batch_size 16 --iters 1000 --epoch 6000 --val_num 10 --baseline_idx 0 --save_path output/models --model_name B0_K240BS32I1000E200_LR1e-4-wdl0.01 --wdl --w_wdl 0.01 --no_val
> ```

还是上面的问题：训练目前似乎只涉及DGFont部分，然后epoch 6000会不会太多了（不确定会不会GD失衡或者overfitting之类的），我们用的是200
