### ISSUE TITLE
如何实现风格插值？

### ISSUE THREAD

**Issue by Chyamble** [wangchi95/CF-Font#24]
老师，您好。在图3中简单的提了一下对基本字体的内容特征进行插值来逼近目标字体，我想知道这个风格插值在代码中应该如何实现？

**Comment by wangchi95** [comment]
由于风格特征是字体级别的，因此无需进行插值就可以得到目标字体的风格特征（一般用给定fewshot字体对应的内容特征均值近似，也可以用我们的SII模块针对性微调该特征）。
如果想实现两个或者多个字体之间的风格插值，可以先分别提取各个字体的风格特征Style vector，然后对这些向量进行线性插值。

**Comment by wangchi95** [comment]
这个issue先关闭了，如果有进一步的问题，可以继续问我:)
