### ISSUE TITLE
关于运行sh scripts/02a_run_ddp.sh时遇到的问题

### ISSUE THREAD

**Issue by tong-song** [wangchi95/CF-Font#25]
老师，你好，我在运行时遇到了importError错误，可是DCN包已经编译好了，
![1700557950938](https://github.com/wangchi95/CF-Font/assets/70563197/f23d945d-0328-4b47-a43e-575f18939cb7)
请问老师原因出在哪里呢，编译DCN的时候我用的torch1.8.0，编译好后我升级到了torch1.10.0，因为会报
![1700558085553](https://github.com/wangchi95/CF-Font/assets/70563197/e689f68d-4aa2-4205-a62d-9c88e02d2ec3)
网上搜索是python版本不匹配。

**Comment by tong-song** [comment]
而且升级torch之后无法在重新编译DCN了。
![1700558430975](https://github.com/wangchi95/CF-Font/assets/70563197/77465ddd-b003-42de-a35d-698048abf10f)
说我cuda不匹配，。
![1700558530190](https://github.com/wangchi95/CF-Font/assets/70563197/8f4d8c90-17dc-49f7-b159-253a390827c2)

**Comment by tong-song** [comment]
老师，问题解决了，我重新配置了环境，pytorch版本是1.8+cu111，DCN编译完成后执行sh scripts/02a_run_ddp.sh时遇到
![image](https://github.com/wangchi95/CF-Font/assets/70563197/e9ef1174-bb88-4f4f-a8bd-36f715855855)
我通过如下方式
![1700575697427](https://github.com/wangchi95/CF-Font/assets/70563197/b272ffbc-197b-49d6-afca-4da37c493160)
然后就能成功运行了。

**Comment by wangchi95** [comment]
很高兴看到这个问题被解决了
