### ISSUE TITLE
NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by OldSixOne** [wangchi95/CF-Font#3]
when sh scripts/02a_run_ddp.sh
I don't know what caused it to appear：  NaN or Inf found in input tensor.
if wdl:
    g_imgrec += calc_wdl(x_rec, x_org) * args.w_wdl # -1 ~ 1

g_imgrec = Nan

what shuold I do?

**Comment by wangchi95** [comment]
> when sh scripts/02a_run_ddp.sh I don't know what caused it to appear： NaN or Inf found in input tensor. if wdl: g_imgrec += calc_wdl(x_rec, x_org) * args.w_wdl # -1 ~ 1
> 
> g_imgrec = Nan
> 
> what shuold I do?

I haven't encountered such a situation, can you upload the `x_rec` and `x_org` when the error occurs?

**Comment by OldSixOne** [comment]
我是在那个网站上下载的字体，随机的选取了300个，240/60，然后我是按照你这个操作流程处理的数据，我在试一下，截图发到这里

**Comment by OldSixOne** [comment]
![Uploading image.png…]()

**Comment by OldSixOne** [comment]
![image](https://user-images.githubusercontent.com/52329210/236743472-153dd81b-64f0-407a-9bba-d1f621c0421f.png)

**Comment by OldSixOne** [comment]
![image](https://user-images.githubusercontent.com/52329210/236743662-dbe2ebd9-d45d-4727-b2dd-348ea9c7e572.png)

**Comment by OldSixOne** [comment]
![image](https://user-images.githubusercontent.com/52329210/236743868-95196e67-4938-4b9d-a475-94f0ee154fcb.png)

**Comment by OldSixOne** [comment]
并不知道为什么会出现nan

**Comment by wangchi95** [comment]
> ![image](https://user-images.githubusercontent.com/52329210/236743868-95196e67-4938-4b9d-a475-94f0ee154fcb.png)

推荐还是进函数看一下哪里会出NaN，我看了一下有可能你喂进去了纯背景的GT（数据生成时，你提供字体不包含给定字符的情况下生成的图片就是纯白的），可以先检查一下数据

**Comment by OldSixOne** [comment]
OK 好的

**Comment by OldSixOne** [comment]
我将纯白色图片删除，将剩下的图片用于训练，还是重新选择新的字体？

**Comment by OldSixOne** [comment]
我发现 ddp 我用1块卡的时间和五块卡的时间是差不多的，然后batch_size 从16 变成64 训练一个epoch的时间会变大

**Comment by wangchi95** [comment]
> 我将纯白色图片删除，将剩下的图片用于训练，还是重新选择新的字体？

最好选择GB2312都有的字体，如果嫌麻烦可以重新选择字符，提出你字体不包含的字符

**Comment by wangchi95** [comment]
> 我发现 ddp 我用1块卡的时间和五块卡的时间是差不多的，然后batch_size 从16 变成64 训练一个epoch的时间会变大

DDP的话 总BS是你设置的单卡BS*卡数
理论上8卡BS8比单卡BS64要快挺多的

**Comment by wangchi95** [comment]
如果速度有问题，看看每张卡GPU利用率，如果GPU利用率不高的话可能瓶颈在数据IO上

**Comment by OldSixOne** [comment]
好的  多谢
