### ISSUE TITLE
关于02a_run_ddp.sh的问题

### ISSUE THREAD

**Issue by Wanglw021010** [wangchi95/CF-Font#30]
老师您好，我在运行02a_run_ddp.sh时发现这样一个报错：
<img width="715" alt="003" src="https://github.com/wangchi95/CF-Font/assets/160603801/3f9dbd23-2f41-4cb6-a951-d36e35b78bd3">
然后我打印了一下哪些参数是梯度为None的，发现全集中在C网络，D网络和G网络没有这种情况
<img width="713" alt="004" src="https://github.com/wangchi95/CF-Font/assets/160603801/e0fba6fe-6a00-4ddb-840e-3619ecd0c7eb">
其实在训练判别器的时候，在train.py中的d_adv_fake.backward()也出现过这个问题，只不过我把d_gp.backward()和d_adv_fake.backward()互换了一下位置就意外地通过了，然后在g_loss.backward()因为相同的问题报错，想请问这是怎么回事，有什么改的方法吗，谢谢！

**Comment by wangchi95** [comment]
@Wanglw021010  我没有遇到过这个问题，不过可以试着排查一下原因。在第一个epoch就出现None了应该是设置的问题，参数是按我的配置来的么？然后数据集需要看看有没有问题（比如有的字体缺字符就可能生成全白的图片）

**Comment by Wanglw021010** [comment]
感谢您的回答，重新配置了一遍问题就解决了！
