### ISSUE TITLE
question about DCN

### ISSUE THREAD

**Issue by haoxia1** [wangchi95/CF-Font#5]
当使用您给的仓库安装DCN总会报错：RuntimeError: Error compiling objects for extension
不知道能否使用其他途径安装的DCN？当我使用其他途径安装成功后显示DCN不存在。
请问您有什么建议吗？感谢！

**Comment by wangchi95** [comment]
我目前没有在网上看到做的比较好的包，需要自己编译或者打包，下代码的时候记得选pytorch_1.0.0分支。目前我的几个环境（torch1.2 1.6 1.8）测试下来都是work的，如果本地环境比较复杂的话可以看一下DCN那块的issue

**Comment by haoxia1** [comment]
> 

是的，我尝试了pytorch1.8，但很奇怪，项目需要安装kornia，然后在安装kornia的时候又自动安装了版本大于1.9的pytorch
![image](https://github.com/wangchi95/CF-Font/assets/62507136/e855d081-e3e9-4e96-b609-3109e9d15200)

**Comment by wangchi95** [comment]
> > 
> 
> 是的，我尝试了pytorch1.8，但很奇怪，项目需要安装kornia，然后在安装kornia的时候又自动安装了版本大于1.9的pytorch ![image](https://user-images.githubusercontent.com/62507136/237321127-e855d081-e3e9-4e96-b609-3109e9d15200.png)

可以指定一下`kornia`的版本来规避conda安装的torch自动升级的问题，版本号可以在这儿查
https://pypi.org/project/kornia/#history

**Comment by haoxia1** [comment]
感谢！已解决。
版本: pytorch=1.6.0, kornia=0.5.0

**Comment by wangchi95** [comment]
问题解决
