### ISSUE TITLE
inference code

### ISSUE THREAD

**Issue by Note-Liu** [wangchi95/CF-Font#7]
By providing  source character images selected from ten basis fonts and  manually set weight values like the first two columns of Fig. 1(a)   how to generated font images? 

Can you provide the relevant code for reference?

**Comment by wangchi95** [comment]
I didn't understand clearly what you meant. 

Seems you can reference the scripts `scripts/04a_run_inf_cf.sh`. If you want to manually generate fonts, you need to provide the basis weights, content fonts (ten basis fonts), and style fonts (fonts with few-shot characters). And if you want to use SII, you need to provide the corresponding few-shot characters of ten basis fonts for style vector fine-tuning. 

All the related data can be generated with the scripts `scripts/01a_gen_date.sh` and `scripts/03c_copy_basis_subset.sh`.

**Comment by Note-Liu** [comment]
Thx!
