### ISSUE TITLE
请问pytorch的版本是多少，DCN装不上，各种报错

### ISSUE THREAD

**Issue by yinminzzy** [wangchi95/CF-Font#9]

**Comment by wangchi95** [comment]
和版本没什么关系 应该都能装上 安装可参考DCN的pytorch1.0.0 branch简介自己编译

**Comment by yinminzzy** [comment]
> 和版本没什么关系 应该都能装上 安装可参考DCN的pytorch1.0.0 branch简介自己编译

还真有点关系，之前环境装的pytorch是1.12.0版本，一直报这个错误，https://blog.csdn.net/qq_40173438/article/details/123830855，把pytorch版本降到1.9.1就没事了，已经安装好了，但是又出现了新的错误：
**Error in magma_getdevice_arch:MAGMA not initialized (call magma_init() first) or bad devide**

就是训练baseline的时候，但是又好像不影响？还在跑着，搞不懂

**Comment by yinminzzy** [comment]
![erro](https://github.com/wangchi95/CF-Font/assets/80611420/1827fea7-b118-46ec-9aa3-9b82f023c114)

**Comment by wangchi95** [comment]
@yinminzzy 我没遇到过这个问题...编译DCN的时候没有报其他错误么 pytorch我主要实验的环境是1.7.1和1.8 之前也试过1.6 使用上都没问题的

**Comment by yinminzzy** [comment]
> @yinminzzy 我没遇到过这个问题...编译DCN的时候没有报其他错误么 pytorch我主要实验的环境是1.7.1和1.8 之前也试过1.6 使用上都没问题的

pytorch 1.9.1版本编译DCN的时候没有任何问题，但是后来再次运行脚本的时候遇到这个问题：
![erro](https://github.com/wangchi95/CF-Font/assets/80611420/f5088ec6-3bb6-4751-975d-640e0619d721)
网上给的原因：https://www.cnblogs.com/tencent-cloud-native/p/15186403.html
1.9版本之后要用torch.distributed.run启动脚本，出现新的错误：
![11](https://github.com/wangchi95/CF-Font/assets/80611420/eefd6690-4c11-4926-9f67-31b5aade0462)
后面放弃1.9这个版本，直接把pytorch降到1.7.1，现在来看没啥问题....还有DCN只能编译一次，不同的虚拟环境必须重新拉一个DCN文件进行编译

**Comment by wangchi95** [comment]
@yinminzzy `--use_env`不加也没事，能用`--nproc_per_node`就行
DCN应该是可以重复编译的 不过需要先删一下生成的缓存文件夹

**Comment by yinminzzy** [comment]
> @yinminzzy `--use_env`不加也没事，能用`--nproc_per_node`就行 DCN应该是可以重复编译的 不过需要先删一下生成的缓存文件夹

好的

**Comment by yinminzzy** [comment]
训练Baseline的时候生成器损失出现负数正常吗？
![1](https://github.com/wangchi95/CF-Font/assets/80611420/95d1c803-5800-422a-9d37-78b094b6882f)

**Comment by wangchi95** [comment]
这看起来是正常的，只需要D loss和G loss相对稳定就行。另外，在训练过程中可以看一下可视化结果是否正常。

**Comment by yinminzzy** [comment]
> 这看起来是正常的，只需要D loss和G loss相对稳定就行。另外，在训练过程中可以看一下可视化结果是否正常。

![1](https://github.com/wangchi95/CF-Font/assets/80611420/dbec0851-6022-4b48-a7e1-afbdf86cdb0a)
感觉不太正常耶

**Comment by yinminzzy** [comment]
![11](https://github.com/wangchi95/CF-Font/assets/80611420/e420b9dd-cccb-4163-83c8-a0223dfafdd7)
想问一下，执行完 sh scripts/03a_get_content_embeddings.sh和sh scripts/03b_cluster_get_cf_basis.sh这两个脚本之后得到10个基础字体的id:
![cf](https://github.com/wangchi95/CF-Font/assets/80611420/7e619fbd-dd0c-4c2f-b92b-d747151e40b6)
是不是要把这些id写到一个txt文件里才能执行 scripts/03c_copy_basis_subset.sh这个脚本，没太看明白，那手动选择会怎么样呢？

**Comment by yinminzzy** [comment]
在执行脚本04a_run_inf_cf.sh后发现并没有生成对可见的240种字体风格推理的结果，在对应的目录下只生成了对不可见的60种字体推理的结果，这是因为执行脚本的时候出现问题了还是什么原因？
![11](https://github.com/wangchi95/CF-Font/assets/80611420/6e4f326d-e42e-4093-b56c-eda27ac19323)

**Comment by wangchi95** [comment]
@yinminzzy 我收到了邮件提醒，好像有新问题但GitHub没有显示，是撤回了么

**Comment by yinminzzy** [comment]
> @yinminzzy 我收到了邮件提醒，好像有新问题但GitHub没有显示，是撤回了么

是的，但是发现是小问题，自己已经解决，感谢~

**Comment by wangchi95** [comment]
这个issue先关闭了，如果有进一步问题，可以继续问我:)
